# Generated by Django 4.2.14 on 2024-07-31 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='default/defprof.png', upload_to='profile_pic/'),
        ),
    ]
