# Generated by Django 4.2.14 on 2024-12-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0008_productmodel_avg_rate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productmodel",
            name="avg_rate",
            field=models.DecimalField(
                decimal_places=1, default=0.0, max_digits=1
            ),
        ),
    ]
