# Generated by Django 4.2.14 on 2025-01-03 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_productmodel_avg_rate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
