# Generated by Django 4.2.14 on 2025-01-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='image',
            new_name='images',
        ),
    ]
