# Generated by Django 4.2.14 on 2025-01-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0019_productimagemodel_delete_productimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="sells",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
