# Generated by Django 4.2.14 on 2024-11-28 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_ordermodel_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.addressmodel'),
        ),
    ]
