# Generated by Django 4.2.14 on 2024-12-13 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsmodel',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='order.ordermodel'),
        ),
    ]
