# Generated by Django 4.2.14 on 2024-12-21 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_alter_orderitemsmodel_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermodel',
            options={'ordering': ('-created_date',)},
        ),
    ]
