# Generated by Django 4.2.14 on 2024-12-28 16:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0007_alter_couponmodel_discount_percent_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="couponmodel",
            options={"ordering": ("-created_date",)},
        ),
        migrations.AddField(
            model_name="couponmodel",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="couponmodel",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
