# Generated by Django 4.2.14 on 2025-01-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "order",
            "0008_alter_couponmodel_options_couponmodel_created_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="order.couponmodel",
            ),
        ),
    ]
