# Generated by Django 4.2.14 on 2025-01-23 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("authority", models.CharField(max_length=40)),
                (
                    "amount",
                    models.DecimalField(decimal_places=0, max_digits=10),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "در حال انتظار"),
                            (2, "موفق"),
                            (3, "نا موفق"),
                        ],
                        default=1,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("updated_date", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_model",
                        to="order.ordermodel",
                    ),
                ),
            ],
        ),
    ]
