# Generated by Django 4.2.14 on 2024-11-29 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_ordermodel_address'),
        ('payment', '0002_remove_paymentmodel_status_code_paymentmodel_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_model', to='order.ordermodel'),
        ),
    ]
